default_platform(:ios)

platform :ios do
  desc "Build and upload a new build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates FLUTTER_BUILD_NUMBER=#{ENV["GITHUB_RUN_NUMBER"]} " \
              "DEVELOPMENT_TEAM=#{ENV["APPLE_TEAM_ID"]} CODE_SIGN_STYLE=Automatic"
    )

    upload_to_testflight(api_key: api_key)
  end
end
